[package]
name = "parquex_nif"
version = "0.4.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["nif_version_2_16"]
nif_version_2_16 = ["rustler/nif_version_2_16"]

[dependencies]
arrow-array = "=59.1.0"
arrow-buffer = "=59.1.0"
arrow-schema = "=59.1.0"
arrow-select = "=59.1.0"
bytes = "=1.12.1"
chrono = { version = "=0.4.45", default-features = false, features = ["std"] }
futures-util = "=0.3.31"
object_store = { version = "=0.14.1", default-features = false, features = ["aws"] }
parquet = { version = "=59.1.0", default-features = false, features = ["arrow", "flate2-zlib-rs", "lz4", "snap", "zstd"] }
rustler = "=0.38.0"
tokio = { version = "=1.47.1", features = ["macros", "rt-multi-thread", "time"] }
zstd = { version = "=0.13.3", default-features = false }
